allow-flight=true
difficulty=normal
enable-command-block=false
enable-rcon=false
enable-status=true
enforce-secure-profile=false
gamemode=survival
generate-structures=true
hardcore=false
level-name=world
level-seed=OUROS_GLOBAL_V1_2026_09_03
level-type=minecraft:normal
max-players=20
motd=Ouros Global V1
online-mode=false
pvp=true
simulation-distance=6
spawn-protection=0
view-distance=10
white-list=false
