package io.autoptu.cobblemon.battlecore;

import java.util.Collections;
import java.util.EnumMap;
import java.util.Map;
import java.util.Objects;

/** Executable compatibility checklist for the currently inspected AutoPTU-Java contract. */
public final class UpstreamCompatibilityMatrix {
    public static final String AUTOPTU_JAVA_SHA = "5eef0c0e8364a4f4a4f8bdb811107895e4cdbe7d";
    public static final String AUTOPTU_PYTHON_SHA = "cd2d31ab9438713629ad3fc65939e8cc622b5a1f";

    public enum Capability {
        CORE_TARGETING, CORE_MOVEMENT_LEGALITY, COMPLETE_MOVEMENT_BEHAVIOR,
        CORE_CALCULATIONS_AND_COMBAT_STATS, ACTION_ECONOMY_AND_INITIATIVE,
        FULL_TURN_ROUND_LIFECYCLE, FULL_STATEFUL_DAMAGE_PIPELINE, COMPLETE_STATUS_LIFECYCLE,
        TERRAIN_WEATHER_HAZARDS_ZONES_REACTIONS, MOVE_SPECIFIC_BEHAVIOR, ABILITIES, ITEMS,
        TRAINER_FEATURES_AND_PERKS, AI_LEGAL_ACTION_INFRASTRUCTURE, AI_TACTICAL_SCORING_POLICY,
        MINECRAFT_COBBLEMON_CRAFTICS_ADAPTER_PLAYBACK
    }

    public enum Support { VERIFIED, PARTIAL, BLOCKING }

    public record Entry(Support support, String contracts, String adapterPolicy) {
        public Entry {
            support = Objects.requireNonNull(support, "support");
            if (contracts == null || contracts.isBlank()) throw new IllegalArgumentException("contracts are required");
            if (adapterPolicy == null || adapterPolicy.isBlank()) throw new IllegalArgumentException("adapterPolicy is required");
        }
    }

    private static final Map<Capability, Entry> ENTRIES = buildEntries();
    private UpstreamCompatibilityMatrix() {}
    public static Entry entry(Capability capability) {
        Entry entry = ENTRIES.get(Objects.requireNonNull(capability, "capability"));
        if (entry == null) throw new IllegalStateException("unmapped upstream capability: " + capability);
        return entry;
    }
    public static Map<Capability, Entry> entries() { return ENTRIES; }
    public static boolean mayProjectAuthoritativeBehavior(Capability capability) { return entry(capability).support() != Support.BLOCKING; }

    private static Map<Capability, Entry> buildEntries() {
        EnumMap<Capability, Entry> entries = new EnumMap<>(Capability.class);
        entries.put(Capability.CORE_TARGETING, verified(
                "MoveSpec, target anchors, footprints, range/area legality, line-of-sight tests and CombatantGeometryState size labels",
                "Project grid inputs and server-owned PTU size labels and render authoritative legal targets only. Combatant model scale, facing, footprint overlap and placement legality must not be invented by the adapter."));
        entries.put(Capability.CORE_MOVEMENT_LEGALITY, verified(
                "MovementGrid, resolved MovementProfile/JumpProfile, Shift/Jump legality, Overland/Swim/Sky and terrain-cost Python parity tests",
                "Supply canonical base movement and adapter-neutral world inputs only. Runtime movement effects such as sprint, Wallrunner, Naturewalk, statuses, abilities, weather, equipment and Trainer Features must be resolved by authoritative PTU contracts before geometry is evaluated; never decide them in Minecraft."));
        entries.put(Capability.COMPLETE_MOVEMENT_BEHAVIOR, blocking(
                "Forced movement, push/pull/knockback, interception and interaction-driven movement are not complete",
                "Do not synthesize forced movement, interception or knockback rules in the adapter."));
        entries.put(Capability.CORE_CALCULATIONS_AND_COMBAT_STATS, verified(
                "Damage Base tables, type effectiveness, STAB, accuracy stages, EvasionProfile, CombatantStatProfile, server-owned mutable CombatStageState, ordered CombatStageHookRegistry with Simple/Defiant/Competitive/Plus [SwSh]/Minus [SwSh] Python parity, centralized CombatStageMutationService/CombatStageMutationResult, generic CombatStageMutationOptions recursive-hook suppression and authoritative SpatialAbilityQuery radius lookup",
                "Supply canonical baseline inputs only. Final evasion, accuracy, combat-stage mutation and combat-stage reaction effects remain core-owned, including move, ability, item, Trainer Feature, status, terrain and temporary-effect contributions. The adapter may project returned starting/base/final stages and emitted semantic events in authoritative order, but must not claim current stages, applied deltas, spatial reaction sources, recursive suppression state or apply stage deltas in Minecraft."));
        entries.put(Capability.ACTION_ECONOMY_AND_INITIATIVE, verified(
                "ActionBudget, typed turn phases, deterministic initiative, Trick Room/League ordering, InitiativeProgressState, authoritative initiative assembly/installation, trainer initiative speed/entry resolution, and RuntimeInitiativePokemonCandidateFactory projection from BattleRuntimeState. BattleEnvironmentState supplies weather/terrain/Tailwind/grounded state; TrainerRuntimeState owns Trainer Feature identities, AP and initiativeModifier; Agility Training, parental-bond-child and initiative-zero flags are read from canonical TemporaryEffectStore. BattleRoundController owns actor selection, START processing and rollover. Analytic resolves against authoritative defender ActionBudget history plus InitiativeProgressState with Python-parity strict cursor semantics",
                "Treat action availability, initiative, trainer initiative modifiers, temporary initiative effects, environment, turn selection, START effect ordering, rollover timing and Trainer resources as core-owned state. Minecraft may seed only canonical battle-start trainer/environment inputs through trusted integration boundaries and render Java results; it must not calculate initiative totals, choose the next actor, rebuild or replace order, provide client-computed modifiers, set temporary initiative flags, reset ActionBudget, set the cursor, execute START hooks, consume skips, spend/restore AP, or decide Analytic eligibility."));
        entries.put(Capability.FULL_TURN_ROUND_LIFECYCLE, partial(
                "BattleRoundController, ordered LifecycleHookRegistry, StatusPhaseEffectRegistry, AbilityPhaseEffectRegistry, PerkPhaseEffectRegistry, CombatantPhaseEffectDispatcher STATUS -> ABILITY -> PERK ordering, structured StatusStateStore, active actor/phase state, authoritative phase/turn-start/turn-end events, advanceInitiativeTurn selection and pending status-skip consumption. InitiativeOrderAssembly/InitiativeAssemblyInstaller, TrainerInitiativeSpeedResolution/TrainerInitiativeEntryResolution, RuntimeInitiativePokemonCandidateFactory, BattleEnvironmentState, TemporaryEffectStore, move-frequency reset, selected round-start cleanup, RoundInjuryHistoryState, BattleRuntimeState.currentRound, damage/injury history rotation, delayed-hit scheduling/binding, Flinch, Strange Tempo, Lancer END, TrainerRuntimeState/controller binding and selected Trainer Features are present",
                "Consume verified lifecycle state/events only and preserve authoritative ordering. Java owns much of initiative rebuilding and selected ROUND_START cleanup, but complete Python start_round parity is still absent: broader send-out effects, remaining status/ability/perk hooks and other lifecycle behaviors remain incomplete. The adapter must never advance currentRound, mutate InitiativeProgressState, assemble initiative, run lifecycle hooks or manufacture missing round effects."));
        entries.put(Capability.FULL_STATEFUL_DAMAGE_PIPELINE, partial(
                "RuntimeMoveResolution, authoritative stats/types/statuses, ordered DamageModifierHookRegistry, pre-damage move hooks and ordered PostDamageHookRegistry/PostDamageHookResult with signed post-damage adjustments; Burn, Pink Pearl, Mega Launcher, actual-HP-loss move-damage-history recording, Aqua Boost/Ignition Boost/Thunder Boost, Power Spot and Type Aura post-result aura selection are parity-backed. Normal Aura Storm is live-wired through canonical MoveSpec Aura keywords, BattleRuntimeState.injuryHistory current injuries and the authoritative global AuraBreakBlockerQuery. Aura Storm [Errata] is live-wired through canonical currentRound, current injuries and RuntimeCombatantState TemporaryEffectStore aura_break_errata entries via AuraBreakErrataAdjustment. PostDamageHookContext receives the core-owned PythonRandom only after accuracy and ordinary DamageResolution consume their RNG. RandomD10PostDamageAbility Adaptability [Errata] and Damp [Errata] are live-wired in RuntimeMoveResolution with parity-backed d10 ordering, Aura Break inversion/expiry, final damage, HP and damage-history mutation. Analytic is live-wired through authoritative defender ActionBudget history and BattleRuntimeState InitiativeProgressState, with Aura Break [Errata] adjustment applied before final HP/history mutation",
                "Consume only core-resolved damage, target HP and ordered semantic events. Current injury count may be initialized only from the frozen canonical battle reservation into BattleRuntimeState.injuryHistory(); previous/last-round injury history and all later injury mutation remain core-owned. Minecraft must never set currentRound, supply or advance the battle RNG, roll or apply Adaptability [Errata]/Damp [Errata] bonuses, determine Aura Break blockers or inversion, inspect/create/expire/clear aura_break_errata temporary effects, select aura sources, calculate signed post-damage adjustments, decide Analytic eligibility, add its +5 damage, inject unported move/ability/item/terrain modifiers, infer missing damage-history semantics, or perform an independent HP mutation. Live ability events and adjusted HP may be mirrored only from Java-emitted semantic events and final MoveResolvedEvent."));
        entries.put(Capability.COMPLETE_STATUS_LIFECYCLE, partial(
                "Canonical status names plus ordered structured StatusEntry/StatusStateStore with parity-backed stacked duplicate storage, StatusPhaseEffectRegistry, StatusApplicationHookRegistry with runtime target-owned ability prevention for Inner Focus/Flinch, Immunity/poison and Insomnia or Vital Spirit/sleep, plus live canonical Safeguard prevention wired by merged PR #155 after target ability prevention with authoritative Infiltrator bypass. Burn damage penalty, Sleep/Paralysis/Freeze evasion effects, status skips, Flinch START/expiry, Strange Tempo Confusion branching and selected Trainer Feature exceptions are present. StatusStateStore preserves repeated normalized names when explicitly stacked while legacy name views remain unique. Current TrainerFeatureEffectRegistry also has parity-backed apply_status/remove_status mutations. Flinch START is part of the normal advanceInitiativeTurn path and its pending skip is consumed before the decision window",
                "Transport server-owned status identity and scalar metadata and render core-emitted status effects/skips only. Selected ability and Safeguard prevention are live, but complete status ticking, cures, durations, source-sensitive behavior, remaining immunities and interactions remain incomplete and core-owned. Safeguard charge consumption/removal and broader blessing-bypass semantics remain unresolved. Minecraft must not interpret or execute those rules."));
        entries.put(Capability.TERRAIN_WEATHER_HAZARDS_ZONES_REACTIONS, partial(
                "Terrain movement costs, weather calculation primitives, BattleEnvironmentState for canonical weather/terrain/Tailwind/grounded inputs, duration-bearing FieldEffectEntry progression and generic HookSource categories/lifecycle seams exist",
                "Project raw world observations separately from trusted PTU environment semantics. Do not classify Minecraft blocks into PTU terrain or derive weather, grounded state, Tailwind, hazards, zones, reactions or forced movement from client/entity observations."));
        entries.put(Capability.MOVE_SPECIFIC_BEHAVIOR, partial(
                "Authoritative movesets, public MoveOption/MoveSpec/MoveCombatProfile metadata, canonical MoveSpec keyword transport with Python move_has_keyword parity, move-frequency enforcement, temporary-effect state, ordered pre-damage move hooks and delayed-hit scheduling/binding/execution for verified combatant-target paths",
                "Resolve frozen move IDs only through trusted server-owned catalog metadata matching public core contracts, including canonical keyword identities. Client/Minecraft may request move identity/target intent only; it may not supply, infer from text, or execute keyword semantics such as push, pull, crash or contact, and unported specials remain core-owned and deferred."));
        entries.put(Capability.ABILITIES, partial(
                "Canonical ability identities, generic HookSource support, AbilityPhaseEffectRegistry including TURN_START START dispatch, CombatStageHookRegistry, PostDamageHookRegistry and parity-backed Mega Launcher, Strange Tempo, Inner Focus, Lancer, Simple, Defiant, Competitive, Plus [SwSh], Minus [SwSh], Aqua Boost, Ignition Boost, Thunder Boost, Power Spot and Type Aura behavior. Normal Aura Storm and Aura Storm [Errata] are live-wired through authoritative injury/round/Aura Break state. Adaptability [Errata] and Damp [Errata] are live post-damage abilities. Analytic is live-wired through server-owned defender action history and InitiativeProgressState. Initiative-time ability inputs such as Slush Rush, Surge Surfer and Chlorophyll [Errata] are resolved from authoritative environment/combatant state. StatusAbilityPreventionResolver is bound into live status application using target-owned RuntimeCombatantState ability suppression for Inner Focus/Flinch, Immunity/poison and Insomnia or Vital Spirit/sleep. Merged PR #155 also live-wires canonical Safeguard prevention after target ability prevention and honors the authoritative Infiltrator bypass",
                "Render only authoritative ability events/results already emitted by the core. Selected status prevention is runtime-wired, but Own Tempo, Oblivious, Run Away, unverified attacker-side defensive-ability bypasses, Safeguard charge consumption/removal and the sources that create/remove ability suppression remain outside this proven boundary. Minecraft must not execute ability hooks, decide status prevention or suppression, calculate ability damage/initiative bonuses, supply RNG or independently alter damage/HP. The remaining ability library stays AutoPTU-Java-owned."));
        entries.put(Capability.ITEMS, partial(
                "BattleRuntimeState heldItemsByCombatant, HeldItemState stable identity, generic rule-effect playback and parity-backed Pink Pearl damage hook; integration has canonical item reservations and a schema-versioned durable item/reservation store with revision-checked atomic commit/release across restart",
                "Project only frozen held-item identity into authoritative runtime state, reserve/commit canonical items server-side, and render verified core item events only. Persisted ownership, quantity and reservation state are authority inputs, not permission to implement healing, capture, crafting, damage, equipment or other unported item effects in Minecraft; never trust client/entity equipment claims."));
        entries.put(Capability.TRAINER_FEATURES_AND_PERKS, partial(
                "Authoritative TrainerRuntimeState stores server-owned Trainer Feature identities, AP, initiativeModifier, generic Feature resources and usage/cooldown bookkeeping; BattleRuntimeState binds combatants to trainer controllers; PerkPhaseLifecycleHook derives owned Features from runtime state; selected status-skip exceptions, Defense Mastery and fixed Link Feature END behavior are parity-backed. TrainerFeaturePrerequisiteResolution, TrainerFeatureContextResolution, TrainerFeatureFrequencyResolution, TrainerFeatureResourceResolution and TrainerFeatureUsageResolution are Python-parity backed. TrainerFeatureExecutionService.executeAuthoritative commits generic bookkeeping only after an applied effect. TrainerFeatureTargetResolution supplies Python-parity generic Pokemon target scopes and TrainerFeatureTrainerTargetResolution supplies parity-backed trainer-target scopes. TrainerFeatureEffectRegistry on the inspected main head has parity-backed heal/heal_active, raise_cs, grant_temp_hp, grant_ap, apply_status and remove_status handlers against authoritative runtime state",
                "Freeze and transport Trainer Feature ownership, battle-start AP, canonical initiative modifier and combatant-controller bindings only from server state. Minecraft/client payloads may not grant Features, decide gates, select or rewrite targets, invoke Feature effects, mutate usage/cooldowns, spend/restore AP/resources or report Feature application. Trainer Features remain partial: bounded heal, combat-stage, temporary-HP, AP and status-effect families do not cover the wider Python effect library, full Feature catalog or every lifecycle/target/resource semantic. Temporary HP damage absorption remains part of the incomplete stateful damage pipeline."));
        entries.put(Capability.AI_LEGAL_ACTION_INFRASTRUCTURE, verified(
                "Runtime-authoritative autobattler action space, affiliation, geometry, action budget, move availability and frequency filtering; advanceInitiativeTurn resolves START effects and pending status skips before the AI receives its decision window. After initiative exhaustion, authoritative initiative assembly/installation and rollover run before the next decision window",
                "AI may choose only from legal choices produced by the core after authoritative rollover/START effects and skips have resolved. The adapter must not supply initiative order or expose a decision window from pre-rollover, pre-START or pre-skip state."));
        entries.put(Capability.AI_TACTICAL_SCORING_POLICY, blocking(
                "Full Python-equivalent tactical scoring/policy is not yet ported",
                "Do not claim Python AI parity or move tactical policy into the Minecraft adapter."));
        entries.put(Capability.MINECRAFT_COBBLEMON_CRAFTICS_ADAPTER_PLAYBACK, partial(
                "Production-remapped Fabric 1.21.1 + Cobblemon 1.7.3 dedicated-server startup is verified. Live PokemonEntity UUID lookup, authoritative relocation, positive HP projection, public BATTLE_STARTED_PRE preemption, identity-only participant capture, canonical identity mapping and atomic opposing-roster reservation have dedicated-server evidence. Player-versus-wild authority composition joins canonical Trainer/Pokemon/item/arena authority with the multi-side roster reservation under one server-issued reservation ID and RNG seed. FabricAuthenticatedPlayerContextResolver validates the external PLAYER UUID against MinecraftServer PlayerManager before canonical PTU encounter context lookup. FabricCanonicalPlayerProvisioning registers on authenticated Fabric JOIN and deterministically maps only the authenticated Minecraft UUID to a server-owned minecraft-player:<uuid> canonical identity. FabricCanonicalPlayerStoreRuntime binds player, encounter-profile, Pokemon and item/reservation repositories plus a WorldScopedCanonicalWildEncounterBlueprintRegistry to the active world lifecycle. PersistentCanonicalPlayerPokemonIdentityBinder validates the authenticated player roster before identity binding. CanonicalWildEncounterBlueprintSource resolves trusted RPG encounter data by canonical encounter ID only; WorldScopedCanonicalWildEncounterBlueprintRegistry is the create-only server-owned implementation. ServerOwnedWildEncounterPreparationService resolves that blueprint before attaching the opaque WILD actor correlation and delegating to ServerOwnedWildEncounterProvisioningService. The provisioner creates deterministic WILD participant/combatant identities, canonical CanonicalEncounterPokemonState values and an encounter seed before ServerOwnedWildEncounterIdentityBinder pairs opaque Cobblemon UUIDs to that roster. FileCanonicalItemReservationRepository and FileCanonicalPokemonRepository provide durable canonical assets, and the two-process restart smoke verifies Trainer/profile/Pokemon/item state across world reopen",
                "Keep support partial. A successful logged-in graphical player encounter is still pending. Trusted world/campaign RPG logic must populate the world-scoped WILD blueprint registry before a Cobblemon correlation is accepted; neither the registry, source contract nor provisioner derives species, level, HP, stats, moves, abilities, held items or outcomes from Cobblemon. The registry is intentionally not durable across restart. The deterministic encounter seed is not yet composed into the later shared reservation seed. Durable WILD provisioning/recovery, encounter-profile creation, cross-aggregate transactions, transaction journaling, partial-commit recovery and reservation expiry/reconciliation remain pending. BattleAuthorityService must continue to re-resolve ownership and quantities before reservation. Zero-HP/faint presentation, complete move animation/semantic cues, full entity lifecycle and complete battle playback remain pending."));
        if (entries.size() != Capability.values().length) throw new IllegalStateException("compatibility matrix must cover every upstream capability");
        return Collections.unmodifiableMap(entries);
    }

    private static Entry verified(String contracts, String policy) { return new Entry(Support.VERIFIED, contracts, policy); }
    private static Entry partial(String contracts, String policy) { return new Entry(Support.PARTIAL, contracts, policy); }
    private static Entry blocking(String contracts, String policy) { return new Entry(Support.BLOCKING, contracts, policy); }
}
