package io.autoptu.cobblemon.battlecore;

import java.util.Collections;
import java.util.EnumMap;
import java.util.Map;
import java.util.Objects;

/** Executable compatibility checklist for the currently inspected AutoPTU-Java contract. */
public final class UpstreamCompatibilityMatrix {
    public static final String AUTOPTU_JAVA_SHA = "63526aa2dce83d0faa22b364705cd36f590d964b";
    public static final String AUTOPTU_PYTHON_SHA = "436b09ceb0811b74dc21924995aa82e56e581061";

    public enum Capability {
        CORE_TARGETING, CORE_MOVEMENT_LEGALITY, COMPLETE_MOVEMENT_BEHAVIOR,
        CORE_CALCULATIONS_AND_COMBAT_STATS, ACTION_ECONOMY_AND_INITIATIVE,
        FULL_TURN_ROUND_LIFECYCLE, FULL_STATEFUL_DAMAGE_PIPELINE, COMPLETE_STATUS_LIFECYCLE,
        TERRAIN_WEATHER_HAZARDS_ZONES_REACTIONS, MOVE_SPECIFIC_BEHAVIOR, ABILITIES, ITEMS,
        TRAINER_FEATURES_AND_PERKS, AI_LEGAL_ACTION_INFRASTRUCTURE, AI_TACTICAL_SCORING_POLICY,
        MINECRAFT_COBBLEMON_CRAFTICS_ADAPTER_PLAYBACK
    }

    public enum Support { VERIFIED, PARTIAL, BLOCKING }

    public record Entry(Support support, String contracts, String adapterPolicy) {
        public Entry {
            support = Objects.requireNonNull(support, "support");
            if (contracts == null || contracts.isBlank()) throw new IllegalArgumentException("contracts are required");
            if (adapterPolicy == null || adapterPolicy.isBlank()) throw new IllegalArgumentException("adapterPolicy is required");
        }
    }

    private static final Map<Capability, Entry> ENTRIES = buildEntries();
    private UpstreamCompatibilityMatrix() {}
    public static Entry entry(Capability capability) {
        Entry entry = ENTRIES.get(Objects.requireNonNull(capability, "capability"));
        if (entry == null) throw new IllegalStateException("unmapped upstream capability: " + capability);
        return entry;
    }
    public static Map<Capability, Entry> entries() { return ENTRIES; }
    public static boolean mayProjectAuthoritativeBehavior(Capability capability) { return entry(capability).support() != Support.BLOCKING; }

    private static Map<Capability, Entry> buildEntries() {
        EnumMap<Capability, Entry> entries = new EnumMap<>(Capability.class);
        entries.put(Capability.CORE_TARGETING, verified(
                "MoveSpec, target anchors, footprints, range/area legality, line-of-sight tests and CombatantGeometryState size labels",
                "Project grid inputs and server-owned PTU size labels and render authoritative legal targets only. Combatant model scale, facing, footprint overlap and placement legality must not be invented by the adapter."));
        entries.put(Capability.CORE_MOVEMENT_LEGALITY, verified(
                "MovementGrid, resolved MovementProfile/JumpProfile, Shift/Jump legality, Overland/Swim/Sky and terrain-cost Python parity tests",
                "Supply canonical base movement and adapter-neutral world inputs only. Runtime movement effects such as sprint, Wallrunner, Naturewalk, statuses, abilities, weather, equipment and Trainer Features must be resolved by authoritative PTU contracts before geometry is evaluated; never decide them in Minecraft."));
        entries.put(Capability.COMPLETE_MOVEMENT_BEHAVIOR, blocking(
                "Forced movement, push/pull/knockback, interception and interaction-driven movement are not complete",
                "Do not synthesize forced movement, interception or knockback rules in the adapter."));
        entries.put(Capability.CORE_CALCULATIONS_AND_COMBAT_STATS, verified(
                "Damage Base tables, type effectiveness, STAB, accuracy stages, EvasionProfile, CombatantStatProfile, server-owned mutable CombatStageState, ordered CombatStageHookRegistry with Simple/Defiant/Competitive/Plus [SwSh]/Minus [SwSh] Python parity, centralized CombatStageMutationService/CombatStageMutationResult, generic CombatStageMutationOptions recursive-hook suppression and authoritative SpatialAbilityQuery radius lookup",
                "Supply canonical baseline inputs only. Final evasion, accuracy, combat-stage mutation and combat-stage reaction effects remain core-owned, including move, ability, item, Trainer Feature, status, terrain and temporary-effect contributions. The adapter may project returned starting/base/final stages and emitted semantic events in authoritative order, but must not claim current stages, applied deltas, spatial reaction sources, recursive suppression state or apply stage deltas in Minecraft."));
        entries.put(Capability.ACTION_ECONOMY_AND_INITIATIVE, verified(
                "ActionBudget, typed turn phases, deterministic initiative, Trick Room/League ordering, InitiativeProgressState, authoritative initiative assembly/installation, trainer initiative speed/entry resolution, and RuntimeInitiativePokemonCandidateFactory projection from BattleRuntimeState. BattleEnvironmentState supplies weather/terrain/Tailwind/grounded state; TrainerRuntimeState owns Trainer Feature identities, AP and initiativeModifier; Agility Training, parental-bond-child and initiative-zero flags are read from canonical TemporaryEffectStore. BattleRoundController owns actor selection, START processing and rollover. Analytic resolves against authoritative defender ActionBudget history plus InitiativeProgressState with Python-parity strict cursor semantics",
                "Treat action availability, initiative, trainer initiative modifiers, temporary initiative effects, environment, turn selection, START effect ordering, rollover timing and Trainer resources as core-owned state. Minecraft may seed only canonical battle-start trainer/environment inputs through trusted integration boundaries and render Java results; it must not calculate initiative totals, choose the next actor, rebuild or replace order, provide client-computed modifiers, set temporary initiative flags, reset ActionBudget, set the cursor, execute START hooks, consume skips, spend/restore AP, or decide Analytic eligibility."));
        entries.put(Capability.FULL_TURN_ROUND_LIFECYCLE, partial(
                "BattleRoundController, ordered LifecycleHookRegistry, StatusPhaseEffectRegistry, AbilityPhaseEffectRegistry, PerkPhaseEffectRegistry, CombatantPhaseEffectDispatcher STATUS -> ABILITY -> PERK ordering, structured StatusStateStore, active actor/phase state, authoritative phase/turn-start/turn-end events, advanceInitiativeTurn selection and pending status-skip consumption. InitiativeOrderAssembly/InitiativeAssemblyInstaller, TrainerInitiativeSpeedResolution/TrainerInitiativeEntryResolution, RuntimeInitiativePokemonCandidateFactory, BattleEnvironmentState, TemporaryEffectStore, move-frequency reset, selected round-start cleanup, RoundInjuryHistoryState, BattleRuntimeState.currentRound, damage/injury history rotation, delayed-hit scheduling/binding, Flinch, Strange Tempo, Lancer END, TrainerRuntimeState/controller binding and selected Trainer Features are present",
                "Consume verified lifecycle state/events only and preserve authoritative ordering. Java owns much of initiative rebuilding and selected ROUND_START cleanup, but complete Python start_round parity is still absent: broader send-out effects, remaining status/ability/perk hooks and other lifecycle behaviors remain incomplete. The adapter must never advance currentRound, mutate InitiativeProgressState, assemble initiative, run lifecycle hooks or manufacture missing round effects."));
        entries.put(Capability.FULL_STATEFUL_DAMAGE_PIPELINE, partial(
                "RuntimeMoveResolution, authoritative stats/types/statuses, ordered DamageModifierHookRegistry, pre-damage move hooks and ordered PostDamageHookRegistry/PostDamageHookResult with signed post-damage adjustments; Burn, Pink Pearl, Mega Launcher, actual-HP-loss move-damage-history recording, Aqua Boost/Ignition Boost/Thunder Boost, Power Spot and Type Aura post-result aura selection are parity-backed. Normal Aura Storm is live-wired through canonical MoveSpec Aura keywords, BattleRuntimeState.injuryHistory current injuries and the authoritative global AuraBreakBlockerQuery. Aura Storm [Errata] is live-wired through canonical currentRound, current injuries and RuntimeCombatantState TemporaryEffectStore aura_break_errata entries via AuraBreakErrataAdjustment. PostDamageHookContext receives the core-owned PythonRandom only after accuracy and ordinary DamageResolution consume their RNG. RandomD10PostDamageAbility Adaptability [Errata] and Damp [Errata] are live-wired in RuntimeMoveResolution with parity-backed d10 ordering, Aura Break inversion/expiry, final damage, HP and damage-history mutation. Analytic is live-wired through authoritative defender ActionBudget history and BattleRuntimeState InitiativeProgressState, with Aura Break [Errata] adjustment applied before final HP/history mutation",
                "Consume only core-resolved damage, target HP and ordered semantic events. Current injury count may be initialized only from the frozen canonical battle reservation into BattleRuntimeState.injuryHistory(); previous/last-round injury history and all later injury mutation remain core-owned. Minecraft must never set currentRound, supply or advance the battle RNG, roll or apply Adaptability [Errata]/Damp [Errata] bonuses, determine Aura Break blockers or inversion, inspect/create/expire/clear aura_break_errata temporary effects, select aura sources, calculate signed post-damage adjustments, decide Analytic eligibility, add its +5 damage, inject unported move/ability/item/terrain modifiers, infer missing damage-history semantics, or perform an independent HP mutation. Live ability events and adjusted HP may be mirrored only from Java-emitted semantic events and final MoveResolvedEvent."));
        entries.put(Capability.COMPLETE_STATUS_LIFECYCLE, partial(
                "Canonical status names plus structured StatusEntry/StatusStateStore, StatusPhaseEffectRegistry, StatusApplicationHookRegistry with Inner Focus Flinch prevention, Burn damage penalty, Sleep/Paralysis/Freeze evasion effects, status skips, Flinch START/expiry, Strange Tempo Confusion branching and selected Trainer Feature exceptions. Flinch START is part of the normal advanceInitiativeTurn path and its pending skip is consumed before the decision window",
                "Transport server-owned status identity and scalar metadata and render core-emitted status effects/skips only. Status application/prevention, START resolution and skip consumption remain core-owned; do not implement missing ticks, cures, immunities, durations, source-sensitive behavior, phase effects or interactions in Minecraft."));
        entries.put(Capability.TERRAIN_WEATHER_HAZARDS_ZONES_REACTIONS, partial(
                "Terrain movement costs, weather calculation primitives, BattleEnvironmentState for canonical weather/terrain/Tailwind/grounded inputs, duration-bearing FieldEffectEntry progression and generic HookSource categories/lifecycle seams exist",
                "Project raw world observations separately from trusted PTU environment semantics. Do not classify Minecraft blocks into PTU terrain or derive weather, grounded state, Tailwind, hazards, zones, reactions or forced movement from client/entity observations."));
        entries.put(Capability.MOVE_SPECIFIC_BEHAVIOR, partial(
                "Authoritative movesets, public MoveOption/MoveSpec/MoveCombatProfile metadata, canonical MoveSpec keyword transport with Python move_has_keyword parity, move-frequency enforcement, temporary-effect state, ordered pre-damage move hooks and delayed-hit scheduling/binding/execution for verified combatant-target paths",
                "Resolve frozen move IDs only through trusted server-owned catalog metadata matching public core contracts, including canonical keyword identities. Client/Minecraft may request move identity/target intent only; it may not supply, infer from text, or execute keyword semantics such as push, pull, crash or contact, and unported specials remain core-owned and deferred."));
        entries.put(Capability.ABILITIES, partial(
                "Canonical ability identities, generic HookSource support, AbilityPhaseEffectRegistry including TURN_START START dispatch, CombatStageHookRegistry, PostDamageHookRegistry and parity-backed Mega Launcher, Strange Tempo, Inner Focus, Lancer, Simple, Defiant, Competitive, Plus [SwSh], Minus [SwSh], Aqua Boost, Ignition Boost, Thunder Boost, Power Spot and Type Aura behavior. Normal Aura Storm and Aura Storm [Errata] are live-wired through authoritative injury/round/Aura Break state. Adaptability [Errata] and Damp [Errata] are live post-damage abilities. Analytic is live-wired through server-owned defender action history and InitiativeProgressState. Initiative-time ability inputs such as Slush Rush, Surge Surfer and Chlorophyll [Errata] are resolved from authoritative environment/combatant state",
                "Render only authoritative ability events/results already emitted by the core. Minecraft must not execute ability hooks, set battle round/environment, inspect temporary effects, decide Aura Break behavior, calculate ability damage or initiative bonuses, select spatial holders, supply RNG, replace initiative order/cursor, or independently alter damage/HP. The remaining ability library stays AutoPTU-Java-owned."));
        entries.put(Capability.ITEMS, partial(
                "BattleRuntimeState heldItemsByCombatant, HeldItemState stable identity, generic rule-effect playback and parity-backed Pink Pearl damage hook; integration also has canonical item reservations",
                "Project only frozen held-item identity into authoritative runtime state, reserve/commit canonical items server-side, and render verified core item events only; do not manufacture unported item effects or trust client/entity equipment claims."));
        entries.put(Capability.TRAINER_FEATURES_AND_PERKS, partial(
                "Authoritative TrainerRuntimeState stores server-owned Trainer Feature identities, AP, initiativeModifier, generic Feature resources and usage/cooldown bookkeeping; BattleRuntimeState binds combatants to trainer controllers; PerkPhaseLifecycleHook derives owned Features from runtime state; selected status-skip exceptions, Defense Mastery and fixed Link Feature END behavior are parity-backed. TrainerFeaturePrerequisiteResolution, TrainerFeatureContextResolution, TrainerFeatureFrequencyResolution, TrainerFeatureResourceResolution and TrainerFeatureUsageResolution are Python-parity backed. TrainerFeatureExecutionService.executeAuthoritative commits generic bookkeeping only after an applied effect. TrainerFeatureTargetResolution supplies Python-parity generic Pokemon target scopes. TrainerFeatureEffectRegistry on the inspected main head has parity-backed heal/heal_active, raise_cs and grant_temp_hp handlers that mutate authoritative BattleRuntimeState targets, combat stages or server-owned temporary HP grants",
                "Freeze and transport Trainer Feature ownership, battle-start AP, canonical initiative modifier and combatant-controller bindings only from server state. Minecraft/client payloads may not grant Features, decide gates, select or rewrite targets, invoke Feature effects, mutate usage/cooldowns, spend/restore AP/resources or report Feature application. Trainer Features remain partial: only bounded generic heal, combat-stage and temporary-HP grant families are ported; AP-specific costs, broader effect coverage and several lifecycle/target families remain incomplete. Temporary HP damage absorption is part of the incomplete stateful damage pipeline, and unknown-effect scaffolding is not permission for the adapter to execute semantics."));
        entries.put(Capability.AI_LEGAL_ACTION_INFRASTRUCTURE, verified(
                "Runtime-authoritative autobattler action space, affiliation, geometry, action budget, move availability and frequency filtering; advanceInitiativeTurn resolves START effects and pending status skips before the AI receives its decision window. After initiative exhaustion, authoritative initiative assembly/installation and rollover run before the next decision window",
                "AI may choose only from legal choices produced by the core after authoritative rollover/START effects and skips have resolved. The adapter must not supply initiative order or expose a decision window from pre-rollover, pre-START or pre-skip state."));
        entries.put(Capability.AI_TACTICAL_SCORING_POLICY, blocking(
                "Full Python-equivalent tactical scoring/policy is not yet ported",
                "Do not claim Python AI parity or move tactical policy into the Minecraft adapter."));
        entries.put(Capability.MINECRAFT_COBBLEMON_CRAFTICS_ADAPTER_PLAYBACK, partial(
                "Production-remapped Fabric 1.21.1 + Cobblemon 1.7.3 dedicated-server startup is verified. Live PokemonEntity UUID lookup, authoritative relocation, positive HP projection, public BATTLE_STARTED_PRE preemption, identity-only participant capture, canonical identity mapping and atomic opposing-roster reservation have dedicated-server evidence. Player-versus-wild authority composition joins canonical Trainer/Pokemon/item/arena authority with the multi-side roster reservation under one server-issued reservation ID and RNG seed. FabricAuthenticatedPlayerContextResolver validates the external PLAYER UUID against MinecraftServer PlayerManager before canonical PTU encounter context lookup. CanonicalPlayerMutationService and VersionedCanonicalStateRepository define revision-guarded server-owned writes. FileVersionedCanonicalStateRepository adds schema-versioned durable single-player persistence, deterministic identity file keys, in-process plus OS-level writer serialization, forced temporary-file contents and required atomic replacement. FabricCanonicalPlayerStoreRuntime binds world-scoped canonical persistence to the active Minecraft world save root and lifecycle. CanonicalPlayerEncounterProfile and FileCanonicalPlayerEncounterProfileRepository add revision-guarded durable roster/consumable/arena selection under that root. PersistentCanonicalPlayerEncounterContextSource resolves an authenticated external UUID through the canonical identity registry, requires the canonical player aggregate and loads those server-owned reservation inputs. The two-process dedicated-server restart smoke now verifies both the Trainer aggregate and encounter profile survive reopening the same world",
                "Keep support partial. A successful logged-in graphical player encounter is still pending. The durable encounter profile is selection state only: independent canonical Pokemon/item aggregate persistence, cross-aggregate transactions, transaction journaling and partial-commit recovery remain pending, and BattleAuthorityService must continue to re-resolve ownership and quantities before reservation. Zero-HP/faint presentation, move animation, semantic cues, RuntimeCombatantState materialization, full entity lifecycle and complete battle playback remain pending. HP projection and battle-trigger interception consume authoritative output only; ServerPlayerEntity, Cobblemon entity state and client replacement aggregates never supply PTU stats, inventory truth, modifiers, legality or outcomes."));
        if (entries.size() != Capability.values().length) throw new IllegalStateException("compatibility matrix must cover every upstream capability");
        return Collections.unmodifiableMap(entries);
    }

    private static Entry verified(String contracts, String policy) { return new Entry(Support.VERIFIED, contracts, policy); }
    private static Entry partial(String contracts, String policy) { return new Entry(Support.PARTIAL, contracts, policy); }
    private static Entry blocking(String contracts, String policy) { return new Entry(Support.BLOCKING, contracts, policy); }
}
