package io.autoptu.cobblemon.fabric;

import com.cobblemon.mod.common.entity.pokemon.PokemonEntity;
import io.autoptu.cobblemon.fabric.admin.FabricRpgVisualProofRuntime;
import io.autoptu.cobblemon.fabric.battle.CobblemonLiveBattleInterceptionSmoke;
import io.autoptu.cobblemon.fabric.battle.FabricAuthenticatedPlayerContextResolverSmoke;
import io.autoptu.cobblemon.fabric.battle.FabricBattleCameraRuntime;
import io.autoptu.cobblemon.fabric.battle.FabricBattleChoiceRuntime;
import io.autoptu.cobblemon.fabric.demo.PlayableBattleTestRuntime;
import io.autoptu.cobblemon.fabric.network.FabricBattleActionNetworking;
import io.autoptu.cobblemon.fabric.network.FabricBattleHpPresentationNetworking;
import io.autoptu.cobblemon.fabric.persistence.FabricCanonicalPlayerProvisioning;
import io.autoptu.cobblemon.fabric.persistence.FabricCanonicalPlayerStoreRestartSmoke;
import io.autoptu.cobblemon.fabric.persistence.FabricCanonicalPlayerStoreRuntime;
import io.autoptu.cobblemon.fabric.presentation.CobblemonLiveHealthSmoke;
import io.autoptu.cobblemon.fabric.presentation.CobblemonLiveReactionPlaybackSmoke;
import io.autoptu.cobblemon.fabric.presentation.CobblemonLiveRelocationSmoke;
import io.autoptu.cobblemon.fabric.rpg.FabricBadgeGateRuntime;
import io.autoptu.cobblemon.fabric.rpg.FabricBagRuntime;
import io.autoptu.cobblemon.fabric.rpg.FabricCanonicalWorldInteractionRuntime;
import io.autoptu.cobblemon.fabric.rpg.FabricCareStatusRuntime;
import io.autoptu.cobblemon.fabric.rpg.FabricCedarRangerProvisioningRuntime;
import io.autoptu.cobblemon.fabric.rpg.FabricCedarRangerProvisioningRuntimeSmoke;
import io.autoptu.cobblemon.fabric.rpg.FabricCedarServiceYardRuntime;
import io.autoptu.cobblemon.fabric.rpg.FabricCraftIngredientDepositRuntime;
import io.autoptu.cobblemon.fabric.rpg.FabricCraftingAssessmentRuntime;
import io.autoptu.cobblemon.fabric.rpg.FabricCraftingCommandRuntime;
import io.autoptu.cobblemon.fabric.rpg.FabricCraftingWorkstationRuntime;
import io.autoptu.cobblemon.fabric.rpg.FabricCraftingWorkstationRuntimeSmoke;
import io.autoptu.cobblemon.fabric.rpg.FabricEncounterStatusRuntime;
import io.autoptu.cobblemon.fabric.rpg.FabricFastTravelRuntime;
import io.autoptu.cobblemon.fabric.rpg.FabricFastTravelRuntimeSmoke;
import io.autoptu.cobblemon.fabric.rpg.FabricFieldCampRuntime;
import io.autoptu.cobblemon.fabric.rpg.FabricFirstJoinOnboardingRuntime;
import io.autoptu.cobblemon.fabric.rpg.FabricGymLeagueRegistrationRuntime;
import io.autoptu.cobblemon.fabric.rpg.FabricGymLeagueRegistrationRuntimeSmoke;
import io.autoptu.cobblemon.fabric.rpg.FabricHealingStationRuntime;
import io.autoptu.cobblemon.fabric.rpg.FabricHealingStationRuntimeSmoke;
import io.autoptu.cobblemon.fabric.rpg.FabricInnRestRuntime;
import io.autoptu.cobblemon.fabric.rpg.FabricInnRestRuntimeSmoke;
import io.autoptu.cobblemon.fabric.rpg.FabricItemStorageRuntime;
import io.autoptu.cobblemon.fabric.rpg.FabricItemStorageTerminalRuntime;
import io.autoptu.cobblemon.fabric.rpg.FabricItemStorageTerminalRuntimeSmoke;
import io.autoptu.cobblemon.fabric.rpg.FabricLocationDiscoveryRuntime;
import io.autoptu.cobblemon.fabric.rpg.FabricMoveTutorRuntime;
import io.autoptu.cobblemon.fabric.rpg.FabricMoveTutorRuntimeSmoke;
import io.autoptu.cobblemon.fabric.rpg.FabricNpcDialogueRuntime;
import io.autoptu.cobblemon.fabric.rpg.FabricNpcDialogueRuntimeSmoke;
import io.autoptu.cobblemon.fabric.rpg.FabricNpcRelationshipRuntime;
import io.autoptu.cobblemon.fabric.rpg.FabricPartyHealingRuntime;
import io.autoptu.cobblemon.fabric.rpg.FabricPartyLeadRuntime;
import io.autoptu.cobblemon.fabric.rpg.FabricPartyManagementRuntime;
import io.autoptu.cobblemon.fabric.rpg.FabricPartyOrderRuntime;
import io.autoptu.cobblemon.fabric.rpg.FabricPartySummaryRuntime;
import io.autoptu.cobblemon.fabric.rpg.FabricPlayerStatusRuntime;
import io.autoptu.cobblemon.fabric.rpg.FabricPokemonDetailRuntime;
import io.autoptu.cobblemon.fabric.rpg.FabricPokemonNicknameRuntime;
import io.autoptu.cobblemon.fabric.rpg.FabricPokemonStorageRuntime;
import io.autoptu.cobblemon.fabric.rpg.FabricPokemonStorageTerminalRuntime;
import io.autoptu.cobblemon.fabric.rpg.FabricPokemonStorageTerminalRuntimeSmoke;
import io.autoptu.cobblemon.fabric.rpg.FabricQuestJournalRuntime;
import io.autoptu.cobblemon.fabric.rpg.FabricRestRuntime;
import io.autoptu.cobblemon.fabric.rpg.FabricRpgCalendarRuntime;
import io.autoptu.cobblemon.fabric.rpg.FabricRpgContent;
import io.autoptu.cobblemon.fabric.rpg.FabricRpgProtectionRuntime;
import io.autoptu.cobblemon.fabric.rpg.FabricRpgProtectionRuntimeSmoke;
import io.autoptu.cobblemon.fabric.rpg.FabricShopCounterRuntime;
import io.autoptu.cobblemon.fabric.rpg.FabricShopCounterRuntimeSmoke;
import io.autoptu.cobblemon.fabric.rpg.FabricShopRuntime;
import io.autoptu.cobblemon.fabric.rpg.FabricStarterCatalogueRuntime;
import io.autoptu.cobblemon.fabric.rpg.FabricStarterSelectionRuntime;
import io.autoptu.cobblemon.fabric.rpg.FabricTargetedInteractionCommandRuntime;
import io.autoptu.cobblemon.fabric.rpg.FabricTrainerPtuActionRuntime;
import io.autoptu.cobblemon.fabric.rpg.FabricTrainerSummaryRuntime;
import io.autoptu.cobblemon.fabric.rpg.FabricTravelCommandRuntime;
import io.autoptu.cobblemon.fabric.rpg.FabricWalletRuntime;
import io.autoptu.cobblemon.fabric.rpg.FabricWorldEventProjectionRuntimeSmoke;
import io.autoptu.cobblemon.fabric.world.CedarMeadowRuntime;
import io.autoptu.cobblemon.fabric.world.MareaInteriorRuntime;
import io.autoptu.cobblemon.fabric.world.MareaVisibleWildPresenceRuntimeSmoke;
import io.autoptu.cobblemon.fabric.world.OurosBuildManifestExportRuntime;
import io.autoptu.cobblemon.fabric.world.OurosGrandPalaceV4ManifestExportRuntime;
import io.autoptu.cobblemon.fabric.world.OurosSignatureBuildRuntime;
import io.autoptu.cobblemon.fabric.world.VisibleWildPokemonEncounterRuntime;
import net.fabricmc.api.ModInitializer;
import net.fabricmc.loader.api.FabricLoader;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/** Dedicated-server Fabric entrypoint for the integration adapter. */
public final class AutoPtuCobblemonFabricAdapter implements ModInitializer {
    private static final Logger LOGGER = LoggerFactory.getLogger("autoptu-cobblemon-rpg");

    @Override
    public void onInitialize() {
        FabricRpgContent.register();
        FabricCanonicalPlayerStoreRuntime.register();
        FabricCanonicalPlayerProvisioning.register();
        FabricCanonicalPlayerStoreRestartSmoke.registerIfEnabled();
        FabricBattleActionNetworking.registerPayloadType();
        FabricBattleHpPresentationNetworking.registerPayloadType();
        if (!FabricLoader.getInstance().isModLoaded("cobblemon")) {
            throw new IllegalStateException("Cobblemon runtime is required by the AutoPTU adapter");
        }
        FabricRpgProtectionRuntime.register();
        FabricRpgProtectionRuntimeSmoke.registerIfEnabled();
        FabricCanonicalWorldInteractionRuntime.register();
        FabricWorldEventProjectionRuntimeSmoke.registerIfEnabled();
        FabricTargetedInteractionCommandRuntime.register();
        FabricFastTravelRuntime.register();
        FabricFastTravelRuntimeSmoke.registerIfEnabled();
        FabricTravelCommandRuntime.register();
        FabricBadgeGateRuntime.register();
        FabricInnRestRuntime.register();
        FabricInnRestRuntimeSmoke.registerIfEnabled();
        FabricFirstJoinOnboardingRuntime.register();
        PlayableBattleTestRuntime.register();
        FabricBattleChoiceRuntime.register();
        FabricBattleCameraRuntime.register();
        FabricEncounterStatusRuntime.register();
        FabricPartyHealingRuntime.register();
        FabricRestRuntime.register();
        FabricHealingStationRuntime.register();
        FabricHealingStationRuntimeSmoke.registerIfEnabled();
        FabricPartySummaryRuntime.register();
        FabricPartyLeadRuntime.register();
        FabricPartyManagementRuntime.register();
        FabricPartyOrderRuntime.register();
        FabricPlayerStatusRuntime.register();
        FabricCareStatusRuntime.register();
        FabricTrainerSummaryRuntime.register();
        FabricBagRuntime.register();
        FabricItemStorageRuntime.register();
        FabricItemStorageTerminalRuntime.register();
        FabricItemStorageTerminalRuntimeSmoke.registerIfEnabled();
        FabricWalletRuntime.register();
        FabricShopRuntime.register();
        FabricShopCounterRuntime.register();
        FabricShopCounterRuntimeSmoke.registerIfEnabled();
        FabricMoveTutorRuntime.register();
        FabricMoveTutorRuntimeSmoke.registerIfEnabled();
        FabricNpcRelationshipRuntime.register();
        FabricNpcDialogueRuntime.register();
        FabricCedarRangerProvisioningRuntime.register();
        FabricCedarServiceYardRuntime.register();
        FabricCedarRangerProvisioningRuntimeSmoke.registerIfEnabled();
        FabricNpcDialogueRuntimeSmoke.registerIfEnabled();
        FabricGymLeagueRegistrationRuntime.register();
        FabricGymLeagueRegistrationRuntimeSmoke.registerIfEnabled();
        FabricLocationDiscoveryRuntime.register();
        FabricPokemonStorageRuntime.register();
        FabricPokemonStorageTerminalRuntime.register();
        FabricPokemonStorageTerminalRuntimeSmoke.registerIfEnabled();
        FabricPokemonDetailRuntime.register();
        FabricPokemonNicknameRuntime.register();
        FabricStarterCatalogueRuntime.register();
        FabricStarterSelectionRuntime.register();
        FabricTrainerPtuActionRuntime.register();
        FabricRpgCalendarRuntime.register();
        FabricQuestJournalRuntime.register();
        FabricCraftingAssessmentRuntime.register();
        FabricCraftingCommandRuntime.register();
        FabricCraftIngredientDepositRuntime.register();
        FabricCraftingWorkstationRuntime.register();
        FabricCraftingWorkstationRuntimeSmoke.registerIfEnabled();
        FabricFieldCampRuntime.register();
        VisibleWildPokemonEncounterRuntime.register();
        CedarMeadowRuntime.register();
        MareaInteriorRuntime.register();
        MareaVisibleWildPresenceRuntimeSmoke.registerIfEnabled();
        FabricRpgVisualProofRuntime.register();
        OurosSignatureBuildRuntime.register();
        OurosBuildManifestExportRuntime.registerIfEnabled();
        OurosGrandPalaceV4ManifestExportRuntime.registerIfEnabled();
        CobblemonLiveRelocationSmoke.registerIfEnabled();
        CobblemonLiveReactionPlaybackSmoke.registerIfEnabled();
        CobblemonLiveHealthSmoke.registerIfEnabled();
        CobblemonLiveBattleInterceptionSmoke.registerIfEnabled();
        FabricAuthenticatedPlayerContextResolverSmoke.registerIfEnabled();
        LOGGER.info("AutoPTU Cobblemon runtime detected: {}", PokemonEntity.class.getName());
        LOGGER.info("AutoPTU Fabric server adapter initialized");
    }
}